name: healvision
description: "Heal Vision App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  
  # All Flutter Packages
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8

  google_fonts: ^6.1.0
  flutter_sliding_box: ^1.1.5

  # --- Splash Screen ----
  flutter_native_splash: ^2.3.1
  # Get packages
  get: ^4.6.6
  get_storage: ^2.1.1
  # ---- other Package -----
  readmore: ^2.2.0
  connectivity_plus: ^5.0.2
  shimmer: ^3.0.0
  image_picker: ^1.0.8
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  lottie: ^3.0.0
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.2.6
  list_wheel_scroll_view_nls: ^0.0.3
  table_calendar: ^3.1.2
  flutter_gemini: ^2.0.3
  dash_chat_2: ^0.0.20
  http: ^1.2.1

  # ----- FireBase -------------
  firebase_core: ^2.29.0
  firebase_storage: ^11.7.1
  firebase_auth: ^4.19.1
  cloud_firestore: ^4.16.1
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/on_boarding/
    - assets/images/
    - assets/images/appointment/
    - assets/home/
    - assets/logo/
    - assets/images/content/
    - assets/images/mood/
    - assets/images/animations/

